pub mod admin;
pub mod chat;
pub mod combat;
pub mod config;
pub mod creature_behavior;
pub mod damage;
pub mod death;
pub mod description;
pub mod events;
pub mod experience;
pub mod item_action;
pub mod item_movement;
pub mod item_multi_action;
pub mod map_query;
pub mod movement;
pub mod pathfinding;
pub mod random;
pub mod skills;
pub mod targeting;

pub type Tick = u64;
